name: Generate Profile Visuals

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Generate Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: OM-SARDAR
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Snake SVGs
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: output
          build_dir: dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
